---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useCache: true
useGitignore: true
dictionaryDefinitions:
  - name: cspell-words
    path: cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
  - javascript
  - typescript
language: en-US
ignorePaths:
  - "/*.json"
  - /.vscode/
  - /cspell-words.txt
  - /cspell.config.yaml
  - /LICENSE
  - /uv.lock
  - /pnpm-lock.yaml
  - /dosraptor/
  - /original_game/
  - /scripts/vendor/
  - /src/game/data/ep1.ts
  - /public/assets/
